name: Matrix uses

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20] # Specify Node.js versions to test
        service: [frontend, backend] # Specify services for matrix execution

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for each matrix combination
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies for the current service
      - name: Install Dependencies
        working-directory: ${{ matrix.service }}
        run: npm install

      # Step 4: Run tests for the current service
      - name: Run Tests
        working-directory: ${{ matrix.service }}
        run: npm test -- --coverage
        env:
          CI: true



      

      
