name: Comprehensive Event Workflow

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *"
  release:
    types:
      - published
  issues:
    types:
      - opened
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'

jobs:
  push-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref_type == 'branch' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Task on Push
        run: echo "Code pushed to branch: ${{ github.ref_name }}!"

  tag-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: On Tag Push
        run: echo "A new tag was pushed: ${{ github.ref_name }}!"

  pull-request-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Task on Pull Request
        run: echo "A pull request was created or updated against branch: ${{ github.base_ref }}!"

  schedule-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' }}
    steps:
      - name: Scheduled Task
        run: echo "This task runs on schedule!"

  release-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    steps:
      - name: On Release Published
        run: echo "A new release was published: ${{ github.event.release.tag_name }}!"

  issue-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issues' }}
    steps:
      - name: On Issue Opened
        run: echo "A new issue has been opened: ${{ github.event.issue.title }}!"

  manual-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Manual Trigger
        run: echo "Triggered manually for the environment: ${{ github.event.inputs.environment }}"
